### PR TITLE
DVSPIMP-3116 - rails_activejob - DF Devspaces

### PR DESCRIPTION
**Pull request by npaurea**
JIRA: https://jira.devfactory.com/browse/DVSPIMP-3116
Jira Contents

* Devspaces Design  Decisions
* Demo video

### CODE REVIEW

**Comment by rajeeshdf** [comment]
@stefan-stanca This PR contains changes related "Spina_sample_app" as well, shouldn't this be independent of that change? You see that the first PR that we have created on upstream repo is still open https://github.com/engineyard/container-services-examples/pull/1

**Comment by stefan-stanca** [comment]
I haven't seen any changes to the sample app here. It is only adding it as a submodule as far as i understand it.

**Comment by rajeeshdf** [comment]
you're not seeing it because it has been merged to master (7c04c3c90ee37f4456e8c0ad458a49d84b8d2fe0) as part of our internal review workflow (#1). But end customer hasn't merged that to the upstream repo https://github.com/engineyard/container-services-examples. So when we submit PR #2 to the upstream repo, it contain both changes.

**Comment by npaurea** [comment]
> @stefan-stanca This PR contains changes related "Spina_sample_app" as well, shouldn't this be independent of that change? You see that the first PR that we have created on upstream repo is still open [engineyard#1](https://github.com/engineyard/container-services-examples/pull/1)

I think that 1) this is a recurring problem in forked repos; 2) this is a unique repo with 2 or 3 different projects; 3) this repo is a corner case;

The dependency point as far as I can see is `.gitmodule` file once this repo has 2 submodules, so independent of the order of the PR we'll fall in this case.

This way, as it is common in several projects we should just document in upstream repo PR the dependency of this one.

**Comment by rajeeshdf** [comment]
I guess this is mistake in our workflow, we shouldn't be merging PRs into forked repositories

**Comment by rajeeshdf** [comment]
Created a new feature branch https://github.com/trilogy-group/container-services-examples/tree/feature/rails-devspaces which has only rails changes. Accepting this PR

**Pull request merged**
